version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: tasky_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: TaskyDev
      POSTGRES_PASSWORD: TaskyDevPass
      POSTGRES_DB: tasky_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
